<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Hardware Fingerprinting Project</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="<?= $this->escape($this->appPath); ?>node_modules/normalize.css/normalize.css">
  <link rel="stylesheet" href="<?= $this->escape($this->appPath); ?>node_modules/material-components-web/dist/material-components-web.css">
  <link rel="stylesheet" href="<?= $this->escape($this->appPath); ?>styles/main.css">
</head>

<body class="mdc-typography">
  <?= $this->yieldView(); ?>
</body>

</html>
